name: 'Sales_Analytics'
version: '1.0.0'
profile: 'Sales-Analytics'



model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  Sales_Analytics:
    staging:
      +materialized: table